"""Init

Revision ID: 864f1771ab8f
Revises: 
Create Date: 2024-08-27 21:43:44.635673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '864f1771ab8f'
down_revision: Union[str, None] = '864f1771ab7o'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meets',
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('companion', sa.String(), nullable=False),
                    sa.Column('type', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meets')
    # ### end Alembic commands ###
