"""Init

Revision ID: 864f1771ab8f
Revises: 
Create Date: 2024-08-27 21:43:44.635673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '864f1771ab7o'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                    sa.Column('command', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), default='text', nullable=False),
                    sa.Column('callback_query', sa.String(), nullable=True),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.UniqueConstraint('command', 'callback_query', name='unique_command_callback_query'),
                    sa.CheckConstraint("type IN ('contact', 'text', 'document')", name='check_aiogram_answer_type'),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
